"""
    This is the main file
    Topic: Book class
    Date: 08 Nov 2023
    Author: Kathleen
"""

from basisclasses.Book import Book

if __name__ == "__main__":

    ### books informations generated by AI
    b1 = Book(bookTitle = "Harry Potter", bookAuthor = "J.K. Rowling", bookEditor = "Scholastic", bookPrice = 10.99)
    b2 = Book(bookTitle = "The Alchemist", bookAuthor = "Paulo Coelho", bookEditor = "HarperOne", bookPrice = 15.99)
    b3 = Book(bookTitle = "1984", bookAuthor = "George Orwell", bookEditor = "Secker & Warburg", bookPrice = 10.75)
    b4 = Book(bookTitle = "Pride and Prejudice", bookAuthor = "Jane Austen", bookEditor = "T. Egerton, Whitehall", bookPrice = 9.99)
    b5 = Book(bookTitle = "The Lord of the Rings", bookAuthor = "J.R.R. Tolkien", bookEditor = "Allen & Unwin", bookPrice = 14.99)

    print(b1)
    print(b2)
    print(b3)
    print(b4)
    print(b5)
